-- 코드를 입력하세요
SELECT a.AUTHOR_ID, a.AUTHOR_NAME, b.CATEGORY, SUM(bo.SALES*b.PRICE) AS TOTAL_SALES
FROM BOOK AS b
LEFT JOIN AUTHOR AS a ON b.AUTHOR_ID = a.AUTHOR_ID
LEFT JOIN BOOK_SALES AS bo ON bo.BOOK_ID = b.BOOK_ID
WHERE bo.SALES_DATE LIKE "2022-01-%"
GROUP BY a.AUTHOR_ID,b.CATEGORY
ORDER BY a.AUTHOR_ID, b.CATEGORY DESC