-- 코드를 입력하세요
SELECT a.AUTHOR_ID, 
       a.AUTHOR_NAME,
       b.CATEGORY, 
       SUM(b.PRICE * bs.SALES) AS TOTAL_SALES
FROM BOOK AS b
LEFT JOIN AUTHOR AS a
ON b.AUTHOR_ID = a.AUTHOR_ID
LEFT JOIN BOOK_SALES AS bs
ON bs.BOOK_ID = b.BOOK_ID
WHERE bs.SALES_DATE	LIKE "2022-01-%"
GROUP BY a.AUTHOR_ID, b.CATEGORY
ORDER BY b.AUTHOR_ID, b.CATEGORY DESC