-- 코드를 입력하세요
SELECT p.PRODUCT_CODE,
       p.PRICE * SUM(os.SALES_AMOUNT) AS SALES
FROM PRODUCT AS p
LEFT JOIN OFFLINE_SALE AS os
ON p.PRODUCT_ID = os.PRODUCT_ID
WHERE os.SALES_AMOUNT IS NOT NULL
GROUP BY p.PRODUCT_ID
ORDER BY SALES DESC, p.PRODUCT_CODE