-- 코드를 입력하세요
SELECT p.PRODUCT_CODE, SUM(os.SALES_AMOUNT)*p.PRICE AS SALES
FROM OFFLINE_SALE AS os
LEFT JOIN PRODUCT AS p
ON os.PRODUCT_ID = p.PRODUCT_ID
GROUP BY os.PRODUCT_ID
ORDER BY SALES DESC, p.PRODUCT_CODE