-- 코드를 입력하세요
SELECT cc.CAR_ID, cc.CAR_TYPE, ROUND(cc.DAILY_FEE*30 * (100-cdp.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS cc
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS cdp
ON cc.CAR_TYPE = cdp.CAR_TYPE
AND cdp.DURATION_TYPE = '30일 이상'
WHERE cc.CAR_TYPE IN ('세단', 'SUV') AND
    cc.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01') AND
    ROUND(cc.DAILY_FEE*30 * (100-cdp.DISCOUNT_RATE) / 100)>=500000 AND
    ROUND(cc.DAILY_FEE*30 * (100-cdp.DISCOUNT_RATE) / 100)<=2000000
ORDER BY FEE DESC, cc.CAR_TYPE, cc.CAR_ID DESC