-- 코드를 입력하세요
SELECT ri.FOOD_TYPE,
       ri.REST_ID,
       ri.REST_NAME,
       ri.FAVORITES
FROM REST_INFO AS ri
WHERE (ri.FOOD_TYPE, ri.FAVORITES) IN (
      SELECT FOOD_TYPE, MAX(FAVORITES)
      FROM REST_INFO 
      GROUP BY FOOD_TYPE)
ORDER BY ri.FOOD_TYPE DESC