SELECT 
    ri.REST_ID,
    ri.REST_NAME,
    ri.FOOD_TYPE,
    ri.FAVORITES,
    ri.ADDRESS,
    ROUND(AVG(rr.REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW as rr
LEFT JOIN REST_INFO as ri
    on rr.REST_ID=ri.REST_ID
WHERE ri.ADDRESS LIKE '서울%'
GROUP BY ri.REST_ID
ORDER BY SCORE DESC, ri.FAVORITES DESC
