-- 코드를 입력하세요
SELECT YEAR(os.SALES_DATE) AS YEAR,
       MONTH(os.SALES_DATE) AS MONTH,
       ui.GENDER AS GENDER,
       COUNT(DISTINCT ui.USER_ID) AS USERS
FROM ONLINE_SALE AS os
LEFT JOIN USER_INFO as ui
ON os.USER_ID = ui.USER_ID
WHERE ui.GENDER IS NOT NULL
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE), ui.GENDER
ORDER BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE), ui.GENDER