-- 코드를 입력하세요
SELECT cr.HISTORY_ID, cr.CAR_ID, DATE_FORMAT(cr.START_DATE,"%Y-%m-%d") AS START_DATE, DATE_FORMAT(cr.END_DATE,"%Y-%m-%d") AS END_DATE,
       CASE WHEN DATEDIFF(DATE_FORMAT(cr.END_DATE,"%Y-%m-%d"),DATE_FORMAT(cr.START_DATE,"%Y-%m-%d"))+1 >=30 THEN "장기 대여"
            ELSE "단기 대여"
       END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS cr
WHERE cr.START_DATE LIKE '2022-09-%'
ORDER BY cr.HISTORY_ID DESC

# SELECT DATE_FORMAT(cr.START_DATE,"%Y-%m-%d")
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS cr