-- 코드를 입력하세요
SELECT fw.WAREHOUSE_ID, 
       fw.WAREHOUSE_NAME, 
       fw.ADDRESS, 
       CASE WHEN fw.FREEZER_YN IS NULL THEN 'N'
            ELSE fw.FREEZER_YN
       END AS FREEZER_YN
FROM FOOD_WAREHOUSE AS fw
WHERE fw.ADDRESS LIKE '경기도%'
ORDER BY fw.WAREHOUSE_ID