-- 코드를 입력하세요
SELECT rh.CAR_ID,
       ROUND(AVG(DATEDIFF(rh.END_DATE,rh.START_DATE))+1,1) AS AVERAGE_DURATION
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS rh
GROUP BY rh.CAR_ID
HAVING AVERAGE_DURATION+1 >= 7
ORDER BY AVERAGE_DURATION DESC, rh.CAR_ID DESC