-- 코드를 작성해주세요
SELECT sd.ROUTE,
       CONCAT(ROUND(SUM(sd.D_BETWEEN_DIST),1),"km") AS TOTAL_DISTANCE,
       CONCAT(ROUND(SUM(sd.D_BETWEEN_DIST)/COUNT(*),2),"km") AS AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE AS sd
GROUP BY sd.ROUTE
ORDER BY SUM(sd.D_BETWEEN_DIST) DESC