-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    COUNT(DISTINCT os.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT os.USER_ID)/(SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021),1) AS PUCHASED_RATIO
FROM ONLINE_SALE as os
LEFT JOIN USER_INFO as ui
ON os.USER_ID = ui.USER_ID
WHERE YEAR(ui.JOINED) = 2021
GROUP BY YEAR(os.SALES_DATE),MONTH(os.SALES_DATE)
ORDER BY YEAR(os.SALES_DATE),MONTH(os.SALES_DATE)