-- 코드를 입력하세요
SELECT rh.CAR_ID,
       CASE 
            WHEN SUM(CASE WHEN '2022-10-16' BETWEEN rh.START_DATE AND rh.END_DATE THEN 1 ELSE 0 END)>0 THEN '대여중'
            ELSE '대여 가능'
       END AS AVAILABILTY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS rh
GROUP BY rh.CAR_ID
ORDER BY rh.CAR_ID DESC