-- 코드를 작성해주세요
SELECT ed.ID,
       CASE WHEN ed.SIZE_OF_COLONY <= 100 THEN 'LOW'
            WHEN 100 < ed.SIZE_OF_COLONY and ed.SIZE_OF_COLONY <= 1000 THEN 'MEDIUM'
            WHEN ed.SIZE_OF_COLONY > 1000 THEN 'HIGH'
       END AS SIZE
FROM ECOLI_DATA AS ed
ORDER BY ed.ID