-- 코드를 작성해주세요
#1~3 -> 1
#4~6 -> 2
#7~9 -> 3
#10~12 -> 4
SELECT CASE WHEN MONTH(ed.DIFFERENTIATION_DATE) <= 3 and MONTH(ed.DIFFERENTIATION_DATE) >= 1 THEN "1Q"
            WHEN MONTH(ed.DIFFERENTIATION_DATE) <= 6 and MONTH(ed.DIFFERENTIATION_DATE) >= 4 THEN "2Q"
            WHEN MONTH(ed.DIFFERENTIATION_DATE) <= 9 and MONTH(ed.DIFFERENTIATION_DATE) >= 7 THEN "3Q"
            WHEN MONTH(ed.DIFFERENTIATION_DATE) <= 12 and MONTH(ed.DIFFERENTIATION_DATE) >= 10 THEN "4Q"
       END AS QUARTER,
       COUNT(*) AS ECOLI_COUNT
FROM ECOLI_DATA AS ed
GROUP BY QUARTER
ORDER BY QUARTER