-- 코드를 입력하세요
SELECT fo.PRODUCT_ID,
       fp.PRODUCT_NAME,
       SUM(fo.AMOUNT * fp.PRICE) AS TOTAL_SALES
FROM FOOD_PRODUCT AS fp
LEFT JOIN FOOD_ORDER AS fo
ON fo.PRODUCT_ID = fp.PRODUCT_ID
WHERE fo.PRODUCE_DATE LIKE '2022-05-%'
GROUP BY fp.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, fo.PRODUCT_ID