-- 코드를 입력하세요
SELECT DC.DR_NAME, DC.DR_ID, DC.MCDP_CD, DATE_FORMAT(DC.HIRE_YMD,"%Y-%m-%d") AS HIRE_YMD
FROM DOCTOR AS DC
WHERE DC.MCDP_CD = 'CS' OR DC.MCDP_CD = 'GS'
ORDER BY DC.HIRE_YMD DESC,DC.DR_NAME