SELECT mp.MEMBER_ID , mp.MEMBER_NAME, mp.GENDER, DATE_FORMAT(mp.DATE_OF_BIRTH,"%Y-%m-%d") AS DATE_OF_BIRTH
FROM MEMBER_PROFILE as mp
WHERE MONTH(DATE_OF_BIRTH) = 3 and mp.GENDER="W" and mp.TLNO IS NOT NULL
ORDER BY mp.MEMBER_ID
