-- 코드를 입력하세요
SELECT HOUR(ao.DATETIME) AS HOUR,
       COUNT(DISTINCT ANIMAL_ID) AS COUNT
FROM ANIMAL_OUTS AS ao
WHERE HOUR(ao.DATETIME)>=9 and HOUR(ao.DATETIME)<=19
GROUP BY HOUR(ao.DATETIME)
ORDER BY HOUR(ao.DATETIME)