SELECT mp.MEMBER_NAME, rr.REVIEW_TEXT , DATE_FORMAT(rr.REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM MEMBER_PROFILE AS mp
LEFT JOIN REST_REVIEW AS rr
ON mp.MEMBER_ID = rr.MEMBER_ID
WHERE mp.MEMBER_ID = 
    (SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    ORDER BY SUM(REST_ID) DESC
    LIMIT 1)
ORDER BY REVIEW_DATE, rr.REVIEW_TEXT