-- 코드를 작성해주세요
SELECT ii.ITEM_ID, ii.ITEM_NAME, ii.RARITY
FROM ITEM_TREE AS it 
LEFT JOIN ITEM_INFO AS ii
ON ii.ITEM_ID = it.ITEM_ID
WHERE it.PARENT_ITEM_ID IN 
      (SELECT ITEM_ID
       FROM ITEM_INFO
       WHERE RARITY = "RARE")
ORDER BY it.ITEM_ID DESC