-- 코드를 작성해주세요
SELECT ed.ID,
       ed.GENOTYPE,
       ed_2.GENOTYPE AS PARENT_GENOTYPE
FROM ECOLI_DATA AS ed
LEFT JOIN ECOLI_DATA AS ed_2
ON ed.PARENT_ID = ed_2.ID
WHERE ed.GENOTYPE & ed_2.GENOTYPE = ed_2.GENOTYPE
ORDER BY ed.ID 