-- 코드를 입력하세요
SELECT MONTH(cr.START_DATE) AS MONTH, cr.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS cr
WHERE cr.START_DATE >= '2022-08-01'AND cr.START_DATE < '2022-11-01' AND 
      cr.CAR_ID IN (SELECT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY WHERE START_DATE >= '2022-08-01'AND START_DATE < '2022-11-01' GROUP BY CAR_ID HAVING COUNT(*)>=5)
GROUP BY MONTH(cr.START_DATE),cr.CAR_ID 
ORDER BY MONTH, cr.CAR_ID DESC