-- 코드를 입력하세요
SELECT MONTH(rh.START_DATE) AS MONTH, rh.CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS rh
WHERE rh.START_DATE>='2022-08-01'
    AND rh.START_DATE<='2022-10-31'
    AND rh.CAR_ID IN 
                (SELECT CAR_ID
                FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
                WHERE START_DATE>='2022-08-01'
                AND START_DATE<='2022-10-31'
                GROUP BY CAR_ID
                HAVING COUNT(*)>=5)
GROUP BY MONTH(rh.START_DATE), rh.CAR_ID
ORDER BY MONTH(rh.START_DATE), rh.CAR_ID DESC