-- 코드를 작성해주세요
SELECT DISTINCT d.ID, d.EMAIL, d.FIRST_NAME, d.LAST_NAME
FROM DEVELOPERS AS d
JOIN SKILLCODES AS s
  ON (s.CODE & d.SKILL_CODE) > 0
WHERE s.NAME = 'Python' or s.NAME = 'C#'
ORDER BY d.ID
