SELECT fi.ID, fni.FISH_NAME, fi.LENGTH
FROM FISH_INFO AS fi
JOIN FISH_NAME_INFO AS fni
  ON fi.FISH_TYPE = fni.FISH_TYPE
WHERE fi.LENGTH = (
    SELECT MAX(fi2.LENGTH)
    FROM FISH_INFO AS fi2
    WHERE fi2.FISH_TYPE = fi.FISH_TYPE
);