-- 코드를 작성해주세요
SELECT he.DEPT_ID, hd.DEPT_NAME_EN, ROUND(SUM(SAL) / COUNT(*),0) AS AVG_SAL
FROM HR_EMPLOYEES AS he
LEFT JOIN HR_DEPARTMENT AS hd
ON he.DEPT_ID = hd.DEPT_ID
GROUP BY he.DEPT_ID
ORDER BY AVG_SAL DESC
