-- 코드를 입력하세요
SELECT U.BOARD_ID,
       U.WRITER_ID,
       U.TITLE,
       U.PRICE,
       CASE WHEN STATUS = "SALE" THEN "판매중"
            WHEN STATUS = "RESERVED" THEN "예약중"
            ELSE "거래완료"
       END AS STATUS
FROM USED_GOODS_BOARD AS U
WHERE YEAR(U.CREATED_DATE) = 2022 AND MONTH(U.CREATED_DATE) = 10 AND DAY(U.CREATED_DATE) = 5
ORDER BY U.BOARD_ID DESC