-- 코드를 입력하세요
SELECT CONCAT("/home/grep/src/",ugb.BOARD_ID,"/",ugf.FILE_ID,ugf.FILE_NAME,ugf.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_BOARD AS ugb
LEFT JOIN USED_GOODS_FILE AS ugf
ON ugb.BOARD_ID = ugf.BOARD_ID
WHERE ugb.BOARD_ID = (SELECT BOARD_ID FROM USED_GOODS_BOARD WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD) ORDER BY FILE_ID DESC)