-- 코드를 입력하세요
SELECT fp.CATEGORY,
       fp.PRICE AS MAX_PRICE,
       fp.PRODUCT_NAME
FROM FOOD_PRODUCT AS fp
WHERE (fp.CATEGORY = '과자' OR fp.CATEGORY = '국' OR fp.CATEGORY = '김치' OR fp.CATEGORY = '식용유')
      AND fp.PRICE IN (SELECT MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY)
GROUP BY CATEGORY
ORDER BY fp.PRICE DESC


