-- 코드를 입력하세요
SELECT fp.CATEGORY, fp.PRICE AS MAX_PRICE, fp.PRODUCT_NAME
FROM FOOD_PRODUCT AS fp
WHERE CATEGORY IN ("과자","국","김치","식용유") AND fp.PRICE IN (SELECT MAX(PRICE) FROM FOOD_PRODUCT GROUP BY CATEGORY)
ORDER BY MAX_PRICE DESC