-- 코드를 작성해주세요
SELECT COUNT(fi.ID) AS FISH_COUNT,
       MAX(fi.LENGTH) AS MAX_LENGTH,
       fi.FISH_TYPE AS FISH_TYPE
FROM FISH_INFO AS fi
GROUP BY fi.FISH_TYPE	
HAVING AVG(GREATEST(fi.LENGTH, 10)) >= 33
ORDER BY fi.FISH_TYPE