-- 코드를 작성해주세요
SELECT COUNT(fi.ID)   AS FISH_COUNT,
       MAX(CASE WHEN fi.LENGTH IS NULL THEN 10 ELSE fi.LENGTH END) AS MAX_LENGTH,
       fi.FISH_TYPE   AS FISH_TYPE
FROM FISH_INFO AS fi
GROUP BY fi.FISH_TYPE
HAVING AVG(CASE WHEN fi.LENGTH IS NULL THEN 10 ELSE fi.LENGTH END) >= 33
ORDER BY fi.FISH_TYPE;